name: utopia_cms_supabase
version: 0.1.0+2
description: Utopia CMS - Supabase
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  supabase_flutter: ^2.0.0
  utopia_cms: ^0.2.1
  utopia_utils: ^0.3.3
  fast_immutable_collections: ^11.1.0

