name: utopia_cms_graphql
version: 0.3.0+1
description: Utopia CMS - GraphQL
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  gql: ^1.0.1
  graphql: ^5.2.3
  utopia_cms: ^0.2.0+1
  utopia_utils: ^0.3.3
  utopia_reporter: ^0.1.0+5
dependency_overrides:
  http: 1.0.0