name: utopia_cms_hasura
version: 0.3.0+6
description: Utopia CMS - Hasura
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  utopia_cms: ^0.2.2
  utopia_cms_graphql: ^0.3.0+6
  utopia_utils: ^0.3.3
  gql: ^1.0.1
  graphql: ^5.2.3
  fast_immutable_collections: ^11.1.0
  utopia_reporter: ^0.1.0+5
