name: utopia_cms_hasura
version: 0.3.0
description: Utopia CMS - Hasura
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:

  # utopia
  utopia_cms: ^0.2.0
  utopia_cms_graphql: ^0.3.0
  utopia_utils: ^0.3.1
  utopia_reporter: ^0.1.0+1

  gql: ^1.0.0+1
  graphql: ^5.1.3
  fast_immutable_collections: ^7.4.3

