name: utopia_cms
version: 0.2.0
description: Utopia CMS - core
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utopia
  utopia_hooks: ^0.4.3+9
  utopia_utils: ^0.3.1
  utopia_arch: ^0.5.0+16
  utopia_widgets: ^0.1.0+1
  utopia_save_file: ^0.2.0+1

  # code generation
  freezed_annotation: ^2.4.1

  # misc
  flutter_spinkit: ^5.2.1
  dropdown_search: ^5.0.6
  shimmer: ^3.0.0
  simple_shadow: ^0.3.1
  country_code_picker: ^3.0.0
  flutter_dropzone: ^3.0.7
  loop_page_view: ^1.2.5
  video_player: ^2.8.3
  fast_immutable_collections: ^7.4.3
  go_router: ^13.2.2
  cross_file: ^0.3.4+1
  cross_file_image: ^1.1.0
  intl: ^0.19.0
  blur: ^3.1.0
  reorderables: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  lints: ^3.0.0

flutter:
  uses-material-design: true
