name: utopia_cms
version: 0.2.1+1
description: Utopia CMS - core
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  utopia_hooks: ^0.4.19+3
  utopia_utils: ^0.3.3
  utopia_arch: ^0.5.1+13
  utopia_widgets: ^0.1.2+1
  utopia_save_file: ^0.2.4+3

  provider: ^6.1.5
  freezed_annotation: ^3.1.0
  flutter_spinkit: ^5.2.2
  dropdown_search: ^6.0.2
  shimmer: ^3.0.0
  simple_shadow: ^0.3.1
  country_code_picker: ^3.4.1
  fast_immutable_collections: ^11.1.0
  go_router: ^17.0.0
  cross_file: ^0.3.5
  cross_file_image: ^1.1.0
  intl: ^0.20.2
  flutter_dropzone: ^4.2.1
  loop_page_view: ^1.2.5
  video_player: ^2.10.0
  blur: ^4.0.2
  reorderables: ^0.6.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.2.3
  lints: ^6.0.0

flutter:
  uses-material-design: true
